## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp09-ipv6-basic', 
	['csma', 'point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp09-ipv6-basic.cc'

    obj = bld.create_ns3_program('exp09-ipv6-basic-raw', 
	['csma', 'point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp09-ipv6-basic-raw.cc'

