## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp04-simpleAdhocWithEnergy', 
	['netanim', 'core', 'mobility', 'wifi','aodv', 'olsr', 'point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp04-simpleAdhocWithEnergy.cc'
