## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp02-simpleAdhoc', 
	['netanim', 'core', 'mobility', 'wifi', 'olsr', 'aodv', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp02-simpleAdhoc.cc'
