## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp07-Red-Droptail', 
	['point-to-point', 'applications', 'internet', 'point-to-point-layout', 'flow-monitor'])
    obj.source = 'exp07-Red-Droptail.cc'
