# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('queue', ['core'])
    module.includes = '.'
    module.source = [
	'model/rr-queue.cc'
	]

    headers = bld(features=['ns3header'])
    headers.module = 'queue'
    headers.source = [
        'model/rr-queue.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

