## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp07-wimax-multicast',
	['wimax', 'netanim', 'core', 'mobility', 'wifi','aodv', 'dsdv', 'olsr', 'dsr',
	 'mobility', 'point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp07-wimax-multicast.cc'
