## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('test-topology-helper', 
	['point-to-point', 'point-to-point-layout', 'applications', 'internet'])
    obj.source = 'test-topology-helper.cc'
