## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp05-simpleRouting', 
	['netanim', 'core', 'mobility', 'wifi','aodv', 'dsdv', 'olsr', 'dsr',
		'point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp05-simpleRouting.cc'
