## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp10-switchedNetwork', 
	['bridge', 'csma', 'point-to-point', 'applications', 'internet'])
    obj.source = 'exp10-switchedNetwork.cc'
