## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp01-simpleTCP', 
	['netanim', 'point-to-point', 'applications', 'internet'])
    obj.source = 'exp01-simpleTCP.cc'
