# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('fixed-dgpsr', ['location-service', 'internet', 'wifi', 'applications', 'mesh', 'point-to-point', 'virtual-net-device'])
    module.source = [
        'model/fixed-dgpsr-ptable.cc',
        'model/fixed-dgpsr-rqueue.cc',
        'model/fixed-dgpsr-packet.cc',
        'model/fixed-dgpsr.cc',
        'helper/fixed-dgpsr-helper.cc',
        ]

    headers = bld(features=['ns3header'])
    headers.module = 'fixed-dgpsr'
    headers.source = [
        'model/fixed-dgpsr-ptable.h',
        'model/fixed-dgpsr-rqueue.h',
        'model/fixed-dgpsr-packet.h',
        'model/fixed-dgpsr.h',
        'helper/fixed-dgpsr-helper.h',
        ]

    
    # bld.ns3_python_bindings()

