## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp08-LongFatPipeTcp', ['point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp08-LongFatPipeTcp.cc'

    obj = bld.create_ns3_program('exp08-LongFatPipeTcp-with-throughput', ['point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp08-LongFatPipeTcp-with-throughput.cc'
