## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('exp06-GlobalSynchro', 
	['point-to-point', 'point-to-point-layout', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'exp06-GlobalSynchro.cc'
